const projects = [
  {
    title      : 'Les ateliers du bien être',
    description: 'Simple website for an association',
    color      : '#E44A2B',
    link       : 'http://www.ateliersdubienetre.org/',
    image      : '/static/img/ateliers.png',
    pro        : true,
    tags       : [ 'web', 'wordpress' ],
  },
  {
    title      : 'Legion Handball',
    description: 'Website about Handball team manager tool',
    color      : '#2C2B2C',
    link       : 'http://legion-handball.com/',
    image      : '/static/img/legion.png',
    pro        : true,
    tags       : [ 'web', 'nodejs' ],
  },
  {
    title      : 'Georges.tech',
    description: 'The accountant bot for liberal workers',
    color      : '#38B39F',
    link       : 'https://georges.tech',
    image      : 'https://www.appvizer.fr/media/application/1868/logo/logo-georges-le-robot-comptable.png',
    pro        : true,
    tags       : [ 'web' ],
  },
  {
    title      : 'Direct Nature',
    description: 'Your specialist in organic and natural products, creates, manufactures and distributes natural products of aromatherapy and diffusers of oils',
    color      : '#389824',
    link       : 'https://directnature.fr',
    image      : 'https://annuaire.laposte.fr/uploads/495/049/49504971000033/logo.jpg',
    pro        : true,
    tags       : [ 'web' ],
  },
  {
    title      : 'Direct Appart',
    description: 'Vacation apartment rental in Lyon, France',
    color      : '#389824',
    link       : 'https://directappart.fr',
    image      : 'https://directappart.fr/wp-content/uploads/2017/01/DSC_2423_compressed.jpg',
    pro        : true,
    tags       : [ 'web' ],
  },
  {
    title      : 'Node.js modules',
    description: 'Node.js packages, mostly about Construct and Electron',
    color      : '#d01919',
    link       : 'https://www.npmjs.com/~armaldio',
    image      : '/static/img/npm.png',
    tags       : [ 'nodejs' ],
  },
  {
    title      : 'Electron For Construct',
    description: 'Bring the power of Electron to your Construct games',
    color      : '#16ab39',
    link       : 'https://github.com/ElectronForConstruct',
    image      : 'https://avatars0.githubusercontent.com/u/24421609?s=200&v=4',
    tags       : [ 'electron', 'construct' ],
  },
  {
    title      : 'Discord',
    description: 'Administrator of the biggest Discord community about Construct',
    color      : '#1678c2',
    link       : 'https://discord.gg/0eLPLj96B4tUr1D3',
    image      : '/static/img/discordandc2.png',
    tags       : [ 'contruct', 'other' ],
  },
  {
    title      : 'Github',
    description: 'Find all of my open sources projects and contributions that are not featured here!',
    color      : '#838383',
    link       : 'https://github.com/armaldio',
    image      : '/static/img/github.png',
    tags       : [ 'other' ],
  },
  {
    title      : 'Construct plugins',
    description: 'A collection of my Construct plugins',
    color      : '#d01919',
    link       : 'https://armaldio.itch.io/',
    image      : '/static/img/itch.jpg',
    tags       : [ 'construct' ],
  },
  {
    title      : 'TIGER',
    description: '<u>T</u>he ult<u>i</u>mate <u>g</u>ame <u>e</u>dito<u>r</u>',
    color      : '#F6D76F',
    link       : 'https://github.com/TIGER-PROJECT/tiger-editor',
    image      : 'https://github.com/TIGER-PROJECT/tiger-editor/raw/master/assets/icons/github/icon.png',
    wip        : true,
    tags       : [ 'web', 'nodejs', 'electron' ],
  },
  {
    title      : 'Android Messages for desktop',
    description: 'A cross-platform Android Messages desktop app',
    color      : '#2C54B8',
    link       : 'https://github.com/Android-Messages-For-Desktop/android-messages-for-desktop',
    image      : 'https://avatars2.githubusercontent.com/u/40691851?s=200&v=4',
    tags       : [ 'web', 'nodejs', 'electron' ],
  },
  {
    title      : 'Addon Installer',
    description: 'Never worry about installing an addon by hand again 💪',
    color      : '#272727',
    link       : 'https://github.com/WebCreationClub/AddonInstaller',
    image      : 'https://github.com/armaldio/AddonInstaller/raw/develop/store/Addoninstaller%20Icon%20(96).png',
    tags       : [ 'web', 'nodejs', 'electron', 'construct' ],
  },
  {
    title      : 'Awesome Construct',
    description: 'An [Awesome](https://github.com/sindresorhus/awesome) list about Construct',
    color      : '#FC60A8',
    link       : 'https://github.com/WebCreationClub/awesome-construct',
    image      : 'https://raw.githubusercontent.com/github/explore/c304601f028774885ef27f72e6fe2d331729d8bc/topics/awesome/awesome.png',
    tags       : [ 'web', 'construct' ],
  },
  /* {
    title      : 'BulbHub',
    description: 'An open source idea voting system for your github repository 💡',
    color      : '#2348CF',
    link       : 'https://github.com/Armaldio/BulbHub',
    image      : 'https://raw.githubusercontent.com/Armaldio/BulbHub/master/logo/BH.png',
    tags       : [ 'web', 'nodejs' ],
    wip        : true,
  }, */
];
export default projects;
