const projects = [
  {
    title      : 'Les ateliers du bien être',
    description: 'Simple website for an association',
    color      : '#E44A2B',
    link       : 'http://www.ateliersdubienetre.org/',
    image      : 'https://armaldio.xyz/img/ateliers.png',
    pro        : true,
    tags       : [ 'web', 'wordpress' ],
  },
  {
    title      : 'Legion Handball',
    description: 'Website about Handball team manager tool',
    color      : '#2C2B2C',
    link       : 'http://legion-handball.com/',
    image      : 'https://armaldio.xyz/img/legion.png',
    pro        : true,
    tags       : [ 'web', 'nodejs' ],
  },
  {
    title      : 'Georges.tech',
    description: 'The accountant bot for liberal workers',
    color      : '#38B39F',
    link       : 'https://georges.tech',
    image      : 'https://www.appvizer.fr/media/application/1868/logo/logo-georges-le-robot-comptable.png',
    pro        : true,
    tags       : [ 'web' ],
  },
  {
    title      : 'Direct Nature',
    description: 'Your specialist in organic and natural products, creates, manufactures and distributes natural products of aromatherapy and diffusers of oils',
    color      : '#389824',
    link       : 'https://directnature.fr',
    image      : 'https://annuaire.laposte.fr/uploads/495/049/49504971000033/logo.jpg',
    pro        : true,
    tags       : [ 'web' ],
  },
  {
    title      : 'Node.js modules',
    description: 'Node.js packages, mostly about Construct and Electron',
    color      : '#d01919',
    link       : 'https://www.npmjs.com/~armaldio',
    image      : 'https://armaldio.xyz/img/npm.png',
    tags       : [ 'nodejs' ],
  },
  {
    title      : 'Electron for Construct 2',
    description: 'Complete set of tools to allow your Construct 2 games to run with Electron',
    color      : '#16ab39',
    link       : 'https://github.com/C2Electron/template',
    image      : 'https://armaldio.xyz/img/electron-logo.png',
    tags       : [ 'electron', 'construct' ],
  },
  {
    title      : 'Discord',
    description: 'Administrator of the biggest Discord community about Construct 2',
    color      : '#1678c2',
    link       : 'https://discord.gg/0eLPLj96B4tUr1D3',
    image      : 'https://armaldio.xyz/img/discordandc2.png',
    tags       : [ 'contruct', 'other' ],
  },
  {
    title      : 'Github',
    description: 'Find all of my open sources projects and contributions that are not featured here!',
    color      : '#838383',
    link       : 'https://github.com/armaldio',
    image      : 'https://armaldio.xyz/img/github.png',
    tags       : [ 'other' ],
  },
  {
    title      : 'Construct plugins',
    description: 'A collection of my Construct plugins',
    color      : '#d01919',
    link       : 'https://armaldio.itch.io/',
    image      : 'https://armaldio.xyz/img/itch.jpg',
    tags       : [ 'construct' ],
  },
  {
    title      : 'TIGER Editor',
    description: 'The ultimate game editor',
    color      : '#F6D76F',
    link       : 'https://github.com/TIGER-PROJECT/tiger-editor',
    image      : 'https://github.com/TIGER-PROJECT/tiger-editor/raw/master/assets/icons/github/icon.png',
    wip        : true,
    tags       : [ 'web', 'nodejs', 'electron' ],
  },
  {
    title      : 'LiveSMS',
    description: 'Open-source, self-hostable Pushbullet clone',
    color      : '#16ab39',
    link       : 'https://github.com/livesms',
    image      : 'https://armaldio.xyz/img/livesms.png',
    tags       : [ 'web', 'nodejs' ],
    deprecated : true,
  },
  {
    title      : 'Android Messages for desktop',
    description: 'A cross-platform Android Messages desktop app',
    color      : '#2C54B8',
    link       : 'https://github.com/Android-Messages-For-Desktop/android-messages-for-desktop',
    image      : 'https://avatars2.githubusercontent.com/u/40691851?s=200&v=4',
    tags       : [ 'web', 'nodejs', 'electron' ],
  },
  {
    title      : 'Addon Installer',
    description: 'Never worry about installing an addon by hand again 💪',
    color      : '#272727',
    link       : 'https://github.com/WebCreationClub/AddonInstaller',
    image      : 'https://github.com/armaldio/AddonInstaller/raw/develop/store/Addoninstaller%20Icon%20(96).png',
    tags       : [ 'web', 'nodejs', 'electron', 'construct' ],
  },
  {
    title      : 'Awesome Construct',
    description: 'An [Awesome](https://github.com/sindresorhus/awesome) list about Construct',
    color      : '#FC60A8',
    link       : 'https://github.com/WebCreationClub/awesome-construct',
    image      : 'https://raw.githubusercontent.com/github/explore/c304601f028774885ef27f72e6fe2d331729d8bc/topics/awesome/awesome.png',
    tags       : [ 'web', 'construct' ],
  },
  {
    title      : 'BulbHub',
    description: 'An open source idea voting system for your github repository 💡',
    color      : '#2348CF',
    link       : 'https://github.com/Armaldio/BulbHub',
    image      : 'https://raw.githubusercontent.com/Armaldio/BulbHub/master/logo/BH.png',
    tags       : [ 'web', 'nodejs' ],
    wip        : true,
  },
  {
    title      : 'TTV Desktop Light',
    description: 'A cross-platform desktop Twitch.tv wrapper with more control and no ads',
    color      : '#514091',
    link       : 'https://github.com/Armaldio/ttv-desktop-lite',
    image      : 'https://raw.githubusercontent.com/Armaldio/ttv-desktop-lite/develop/images/twitchy_icon.png',
    tags       : [ 'web', 'nodejs', 'electron' ],
    wip        : true,
  },
  {
    title      : 'Content Loader Designer',
    description: 'A visual app to generate Vue and React content loaders',
    color      : '#272727',
    link       : 'https://github.com/Armaldio/content-loader-designer',
    image      : 'https://fakeimg.pl/80x80/424242/fff/?text=?',
    tags       : [ 'web' ],
    wip        : true,
  },
  {
    title      : 'DonateHub',
    description: 'A personal page to share all your donation links',
    color      : '#272727',
    link       : 'https://github.com/Armaldio/DonateLinks',
    image      : 'https://fakeimg.pl/80x80/424242/fff/?text=?',
    tags       : [ 'web', 'nodejs' ],
    wip        : true,
  },
  {
    title      : 'DeskGet',
    description: 'Create your very own desktop widget with html, css and javascript with node.js access',
    color      : '#272727',
    link       : 'https://github.com/Armaldio/deskget',
    image      : 'https://fakeimg.pl/80x80/424242/fff/?text=?',
    tags       : [ 'nodejs', 'electron' ],
    wip        : true,
  },
];
export default projects;
